#!/usr/bin/env bash

function start_minecraft()
{
    cd /data/runtime || exit 1
    exec java -server -Xms128M -jar /data/runtime/minecraft_server.jar nogui
}

if [[ -f /data/runtime/server.properties ]]; then
    start_minecraft
else
    start_minecraft &
    pid=$!
    sleep 10
    MCRCON_PASS="$(ruby -rsecurerandom -e 'puts SecureRandom.hex(20)')"
    sed -i 's/white-list=.*/white-list=true/g' /data/runtime/server.properties
    sed -i 's/enable-rcon=.*/enable-rcon=true/g' /data/runtime/server.properties
    echo "rcon.password=$MCRCON_PASS" >> /data/runtime/server.properties
    /scripts/mcrcon -p "$MCRCON_PASS" "op xucheng"
    kill -9 "$pid"
    start_minecraft
fi

