#!/usr/bin/env bash

function start_minecraft()
{
    [[ -f /data/runtime/eula.txt ]] || echo "eula=true" > /data/runtime/eula.txt
    cd /data/runtime || exit 1
    exec java -server -Xms256M -jar /minecraft/minecraft_server.jar nogui
}

mkdir -p /data/runtime
# make it easier to update runtime folder inside docker.
if [[ -d /data/runtime_update ]]; then
    [[ ! -d /data/runtime_backup ]] || rm -rf /data/runtime_backup
    mv /data/runtime /data/runtime_backup
    mv /data/runtime_update /data/runtime
fi

if [[ -f /data/runtime/server.properties ]]; then
    start_minecraft
else
    echo "stop" | start_minecraft
    MCRCON_PASS="$(ruby -rsecurerandom -e 'puts SecureRandom.hex(20)')"
    sed -i.bak '/white-list=.*/d' /data/runtime/server.properties
    sed -i.bak '/enable-rcon=.*/d' /data/runtime/server.properties
    rm /data/runtime/server.properties.bak
    tee -a /data/runtime/server.properties >/dev/null <<EOS
white-list=true
enable-rcon=true
rcon.password=$MCRCON_PASS
EOS
    (
        sleep 20
        while read -r name; do
            [[ -n "$name" ]] || continue
            /scripts/mcrcon -p "$MCRCON_PASS" "op $name"
        done < /minecraft/ops.txt
    ) &
    start_minecraft
fi

