#!/usr/bin/env bash

function start_minecraft()
{
    [[ -d /data/runtime ]] || mkdir -p /data/runtime
    [[ -f /data/runtime/eula.txt ]] || echo "eula=true" > /data/runtime/eula.txt
    cd /data/runtime || exit 1
    exec java -server -Xms128M -jar /minecraft/minecraft_server.jar nogui
}

if [[ -f /data/runtime/server.properties ]]; then
    start_minecraft
else
    echo "stop" | start_minecraft
    MCRCON_PASS="$(ruby -rsecurerandom -e 'puts SecureRandom.hex(20)')"
    sed -i.bak '/white-list=.*/d' /data/runtime/server.properties
    sed -i.bak '/enable-rcon=.*/d' /data/runtime/server.properties
    rm /data/runtime/server.properties.bak
    tee -a /data/runtime/server.properties >/dev/null <<EOS
white-list=true
enable-rcon=true
rcon.password=$MCRCON_PASS
EOS
    (sleep 10; /scripts/mcrcon -p "$MCRCON_PASS" "op xucheng") &
    start_minecraft
fi

